# Generated by Django 3.2.8 on 2021-11-20 04:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_sum', models.IntegerField(verbose_name='deposit amount')),
                ('period', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='period in days')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesDepositsBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('usd', models.CharField(max_length=3, verbose_name='currency')),
                ('usd_buy', models.FloatField(verbose_name='dollar purchase rate')),
                ('usd_sale', models.FloatField(verbose_name='dollar selling rate')),
                ('eur', models.CharField(max_length=3, verbose_name='currency')),
                ('eur_buy', models.FloatField(verbose_name='euro purchase rate')),
                ('eur_sale', models.FloatField(verbose_name='euro selling rate')),
                ('rub', models.CharField(max_length=3, verbose_name='currency')),
                ('rub_buy', models.FloatField(verbose_name='purchase rate RUB')),
                ('rub_sale', models.FloatField(verbose_name='sale rate RUB')),
                ('rate_byn', models.FloatField(verbose_name='deposit rate BYN')),
                ('rate_usd', models.FloatField(verbose_name='deposit rate USD')),
                ('rate_eur', models.FloatField(verbose_name='deposit rate EUR')),
                ('rate_rub', models.FloatField(verbose_name='deposit rate RUB')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitDepositsClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('profit_usd', models.FloatField(verbose_name='income at the deposit rate of USD')),
                ('profit_eur', models.FloatField(verbose_name='income at the deposit rate of EUR')),
                ('profit_rub', models.FloatField(verbose_name='income at the deposit rate of RUB')),
                ('profit_byn', models.FloatField(verbose_name='income at the deposit rate of BYN')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.client')),
            ],
        ),
    ]
