# Generated by Django 3.2.8 on 2021-11-10 22:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_sum', models.IntegerField(verbose_name='сумма вклада')),
                ('period', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='период')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesDepositsBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('usd', models.CharField(max_length=3, verbose_name='валюта')),
                ('usd_buy', models.FloatField(verbose_name='курс покупки доллара')),
                ('usd_sale', models.FloatField(verbose_name='курс продажи доллара')),
                ('eur', models.CharField(max_length=3, verbose_name='валюта')),
                ('eur_buy', models.FloatField(verbose_name='курс покупки евро')),
                ('eur_sale', models.FloatField(verbose_name='курс продажи евро')),
                ('rub', models.CharField(max_length=3, verbose_name='валюта')),
                ('rub_buy', models.FloatField(verbose_name='курс покупки рос.рубли')),
                ('rub_sale', models.FloatField(verbose_name='курс продажи рос.рубли')),
                ('rate_byn', models.FloatField(verbose_name='ставка вклада BYN')),
                ('rate_usd', models.FloatField(verbose_name='ставка вклада USD')),
                ('rate_eur', models.FloatField(verbose_name='ставка вклада EUR')),
                ('rate_rub', models.FloatField(verbose_name='ставка вклада RUB')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitDepositsClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('profit_usd', models.FloatField(verbose_name='доход по ставке вклада USD')),
                ('profit_eur', models.FloatField(verbose_name='доход по ставке вклада EUR')),
                ('profit_rub', models.FloatField(verbose_name='доход по ставке вклада RUB')),
                ('profit_byn', models.FloatField(verbose_name='доход по ставке вклада BYN')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.client')),
            ],
        ),
    ]
