# Generated by Django 3.2.8 on 2021-11-01 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesDepositsBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('usd', models.CharField(max_length=3, verbose_name='валюта')),
                ('usd_buy', models.FloatField(verbose_name='курс покупки доллара')),
                ('usd_sale', models.FloatField(verbose_name='курс продажи доллара')),
                ('eur', models.CharField(max_length=3, verbose_name='валюта')),
                ('eur_buy', models.FloatField(verbose_name='курс покупки евро')),
                ('eur_sale', models.FloatField(verbose_name='курс продажи евро')),
                ('rub', models.CharField(max_length=3, verbose_name='валюта')),
                ('rub_buy', models.FloatField(verbose_name='курс покупки рос.рубли')),
                ('rub_sale', models.FloatField(verbose_name='курс продажи рос.рубли')),
                ('rate_byn', models.FloatField(verbose_name='ставка вклада BYN')),
                ('rate_usd', models.FloatField(verbose_name='ставка вклада USD')),
                ('rate_eur', models.FloatField(verbose_name='ставка вклада EUR')),
                ('rate_rub', models.FloatField(verbose_name='ставка вклада RUB')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('password', models.CharField(max_length=150, verbose_name='пароль')),
                ('deposit_sum', models.IntegerField(verbose_name='сумма вклада')),
                ('period', models.IntegerField(verbose_name='период')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.coursesdepositsbank')),
            ],
        ),
    ]
