# Generated by Django 3.2.8 on 2021-11-20 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='deposit_sum',
            field=models.IntegerField(verbose_name='deposit amount'),
        ),
        migrations.AlterField(
            model_name='client',
            name='period',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='period in days'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='eur',
            field=models.CharField(max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='eur_buy',
            field=models.FloatField(verbose_name='euro purchase rate'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='eur_sale',
            field=models.FloatField(verbose_name='euro selling rate'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='rate_byn',
            field=models.FloatField(verbose_name='deposit rate BYN'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='rate_eur',
            field=models.FloatField(verbose_name='deposit rate EUR'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='rate_rub',
            field=models.FloatField(verbose_name='deposit rate RUB'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='rate_usd',
            field=models.FloatField(verbose_name='deposit rate USD'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='rub',
            field=models.CharField(max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='rub_buy',
            field=models.FloatField(verbose_name='purchase rate RUB'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='rub_sale',
            field=models.FloatField(verbose_name='sale rate RUB'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='usd',
            field=models.CharField(max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='usd_buy',
            field=models.FloatField(verbose_name='dollar purchase rate'),
        ),
        migrations.AlterField(
            model_name='coursesdepositsbank',
            name='usd_sale',
            field=models.FloatField(verbose_name='dollar selling rate'),
        ),
        migrations.AlterField(
            model_name='profitdepositsclient',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='profitdepositsclient',
            name='profit_byn',
            field=models.FloatField(verbose_name='income at the deposit rate of BYN'),
        ),
        migrations.AlterField(
            model_name='profitdepositsclient',
            name='profit_eur',
            field=models.FloatField(verbose_name='income at the deposit rate of EUR'),
        ),
        migrations.AlterField(
            model_name='profitdepositsclient',
            name='profit_rub',
            field=models.FloatField(verbose_name='income at the deposit rate of RUB'),
        ),
        migrations.AlterField(
            model_name='profitdepositsclient',
            name='profit_usd',
            field=models.FloatField(verbose_name='income at the deposit rate of USD'),
        ),
    ]
